name: PHPStan

on:
  pull_request:
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:0350984fa181805de159e04669b9d7b24eac50bdcd3cfe27e60ea774b3e5846d
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Composer
        run: composer install

      - name: PHPStan
        uses: docker://ghcr.io/sgoettsch/docker-phpstan:latest-php8.1@sha256:0350984fa181805de159e04669b9d7b24eac50bdcd3cfe27e60ea774b3e5846d
        with:
          args: analyze --error-format=table /github/workspace
